apiVersion: v1
kind: Service
metadata:
  name: multmatrix-service
spec:
  type: NodePort
  selector:
    app: multmatrix
  ports:
    - protocol: TCP
      port: 30002
      targetPort: 30002
      nodePort: 31525

