apiVersion: v1
kind: Service
metadata:
  name: filemanager-service
spec:
  type: NodePort
  selector:
    app: filemanager
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 30001
      nodePort: 31524

