apiVersion: v1
kind: Service
metadata:
 name: bootcamp-entrypoint
 namespace: default
spec:
 type: NodePort
 selector:
  app: bootcamp
 ports:
 - port:      8080
   targetPort: 8080
   nodePort:   31000
 externalTrafficPolicy: Cluster
